# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgfdXXpVHSe1d9XV84o1UR0Y5jp9P2oP
"""
#import libraries and packages with aliases
import sqlite3
from sqlite3 import connect
import pandas as pd
import numpy as np
import streamlit as st
from PIL import Image

#open and display header image/title
image = Image.open('Logo-KDT-JU.webp')
st.title("Maliah and Eliana's Search App :)")
st.image(image)

#open connection to allow access to our database 
con = sqlite3.connect("ecsel_database.db")
#interact with database and create tables with specific columns
df_countryList = pd.read_sql('SELECT countries.Country, countries.Acronym FROM countries', con)
df_projects = pd.read_sql('SELECT Projects.projectID, Projects.year, Projects.acronym FROM Projects', con)
df_participants = pd.read_sql('SELECT  organizations.projectID, organizations.country, organizations.shortName, organizations.name, organizations.activityType, organizations.organizationURL, organizations.ecContribution, organizations.projectAcronym FROM organizations ', con)
#close connection
con.close()

# Country selection using a dropdown menu 
country = st.selectbox('pick', ['BE', 'BG', 'CZ', 'DK', 'DE', 'EE', 'IE','EL','ES','FR','HR','IT','CY','LV','LT','LU','HU','MT','NL','AT','PL','PT','RO','SI','SK','FI','SE'])

#creating table with data specific to the selected country
df_new = df_participants[df_participants["country"] == country]
df_pryear = df_projects[["projectID", "year"]]
df_new = pd.merge(df_new, df_pryear, how ="left", on="projectID")

#create table by country selection, using ORDER BY to order the table in descending order, using WHERE to match to the selected country

con = sqlite3.connect("ecsel_database.db")
df_best = pd.read_sql(f'SELECT organizations.shortname, organizations.name, organizations.activityType, organizations.organizationURL, organizations.ecContribution, country  FROM organizations WHERE country="{country}" ORDER BY ecContribution DESC', con)


df_better = pd.read_sql(f'SELECT organizations.shortname, organizations.name, organizations.activityType, organizations.projectAcronym, country FROM organizations WHERE country="{country}"', con)

con.close()

st.write("Participants Dataframe") # label for table
st.dataframe(df_best) #display data and creation of download button
csv_c = df_best.to_csv().encode('utf-8')
st.download_button(
     label="Download Participants Dataframe as CSV",
     data=csv_c,
     file_name=f'df_partipants.csv',
     mime='text/csv',)

st.write("Project Coordinators") # label for table

st.dataframe(df_better) #display data and creation of download button
csv_c2 = df_better.to_csv().encode('utf-8')
st.download_button(
     label="Download Project Coordinators as CSV",
     data=csv_c2,
     file_name=f'df_projects.csv',
     mime='text/csv',)

#bar graph creation, followed by display command in Streamlit
df_counterYear = df_new.groupby("year").sum().ecContribution
st.bar_chart(df_counterYear)
st.balloons()

